import { notFound } from "next/navigation";
import { getDictionary, isLocale, type Locale } from "@/lib/i18n";
import { buildPageMetadata } from "@/lib/seo";

export async function generateMetadata({ params }: { params: Promise<{ lang: string }> }) { const { lang } = await params; if (!isLocale(lang)) return {}; const d = getDictionary(lang); return buildPageMetadata(lang, "/about", d.page.aboutTitle, d.page.aboutText); }

export default async function About({ params }: { params: Promise<{ lang: string }> }) {
  const { lang } = await params; if (!isLocale(lang)) notFound(); const locale = lang as Locale; const d = getDictionary(locale);
  const extra = locale === "ru" ? ["Agile Business объединяет стратегический консалтинг, аналитику, дизайн и разработку в одной команде. Мы подключаемся к бизнес-результату: росту продаж, прозрачности управления, запуску продукта или автоматизации процессов.", "Каждый проект ведём короткими понятными этапами. Команда заказчика видит логику решений, текущий прогресс и следующие шаги без закрытых процессов и лишней бюрократии."] : locale === "hy" ? ["Agile Business-ը մեկ թիմում միավորում է ռազմավարությունը, վերլուծությունը, դիզայնը և մշակումը։ Մենք աշխատում ենք բիզնես արդյունքի հետ՝ վաճառքի աճ, կառավարման թափանցիկություն, արտադրանքի գործարկում կամ գործընթացների ավտոմատացում։", "Յուրաքանչյուր նախագիծ վարում ենք կարճ և հասկանալի փուլերով։ Պատվիրատուի թիմը տեսնում է որոշումների տրամաբանությունը, ընթացիկ առաջընթացը և հաջորդ քայլերը։"] : ["Agile Business brings strategy, analytics, design and development together in one team. We engage with the business outcome, not an isolated task list.", "Every engagement follows clear, short stages. The client team sees the reasoning, current progress and next steps throughout the project."];
  return <><section className="page-hero about-hero shell"><div className="about-title-row"><h1>{d.page.aboutTitle}</h1><p>{d.page.aboutText}</p></div><div className="about-copy">{extra.map(item => <p key={item}>{item}</p>)}</div></section><section className="section about-process shell"><div className="principles"><h2>{d.method.title}</h2><ol>{d.page.aboutPrinciples.map((item, index) => <li key={item}><span>0{index + 1}</span><p>{item}</p><i aria-hidden="true">↗</i></li>)}</ol></div></section></>;
}
