import { notFound } from "next/navigation";
import { isLocale } from "@/lib/i18n";
import { RegionalContactDetails, RegionalEmail } from "@/components/regional-contact-details";

export default async function Privacy({ params }: { params: Promise<{ lang: string }> }) {
  const { lang } = await params;
  if (!isLocale(lang)) notFound();
  const ru = lang === "ru";
  const pl = lang === "pl";

  return (
    <article className="legal shell">
      <header><span>{ru ? "Редакция от 1 августа 2026 года" : pl ? "Wersja z 1 sierpnia 2026 r." : "Effective August 1, 2026"}</span><h1>{ru ? "Политика обработки персональных данных" : pl ? "Polityka przetwarzania danych osobowych" : "Personal Data Processing Policy"}</h1></header>
      <p>{ru ? "Настоящая Политика определяет порядок и условия обработки персональных данных пользователей сайта agile-business-pro.com компанией Agile Business (далее — Оператор)." : pl ? "Niniejsza Polityka opisuje, w jaki sposób Agile Business (Administrator) przetwarza dane osobowe przekazywane za pośrednictwem serwisu agile-business-pro.com." : "This Policy describes how Agile Business (the Controller) processes personal data submitted through agile-business-pro.com."}</p>
      <h2>{ru ? "1. Общие положения" : pl ? "1. Postanowienia ogólne" : "1. General provisions"}</h2>
      <p>{ru ? "Политика составлена с учётом требований Федерального закона № 152-ФЗ «О персональных данных». Оператор обрабатывает данные законно, добросовестно и только в объёме, необходимом для заявленных целей." : pl ? "Administrator przetwarza dane zgodnie z prawem, rzetelnie i wyłącznie w zakresie niezbędnym do realizacji celów określonych poniżej, z uwzględnieniem wymagań RODO." : "The Controller processes data lawfully, fairly and only to the extent necessary for the purposes stated below."}</p>
      <h2>{ru ? "2. Какие данные обрабатываются" : pl ? "2. Jakie dane przetwarzamy" : "2. Data we process"}</h2>
      <p>{ru ? "Имя, номер телефона, адрес электронной почты, название компании, содержание обращения, выбранные параметры расчёта проекта, а также технические сведения, передаваемые браузером: IP-адрес, cookie, тип устройства и данные о посещении страниц." : pl ? "Imię i nazwisko, numer telefonu, adres e-mail, nazwa firmy, treść zapytania, wybrane parametry wyceny projektu oraz dane techniczne przekazywane przez przeglądarkę, takie jak adres IP, pliki cookie, typ urządzenia i aktywność w serwisie." : "Name, phone number, email, company, inquiry details, project estimate selections and technical browser data such as IP address, cookies, device type and page activity."}</p>
      <h2>{ru ? "3. Цели и правовые основания" : pl ? "3. Cele i podstawy prawne" : "3. Purposes and legal basis"}</h2>
      <p>{ru ? "Данные используются для ответа на обращение, подготовки коммерческого предложения, заключения и исполнения договора, улучшения сайта и обеспечения его безопасности. Основания обработки — согласие пользователя, действия по запросу пользователя до заключения договора и исполнение договора." : pl ? "Dane wykorzystujemy do obsługi zapytań, przygotowania ofert, zawierania i realizacji umów, doskonalenia serwisu oraz zapewnienia jego bezpieczeństwa. Podstawą przetwarzania jest zgoda, działania przed zawarciem umowy, realizacja umowy oraz prawnie uzasadniony interes Administratora." : "Data is used to respond to inquiries, prepare proposals, perform contracts, improve the website and protect its security. Processing is based on consent, pre-contractual steps and contract performance."}</p>
      <h2>{ru ? "4. Порядок, сроки хранения и передача" : pl ? "4. Sposób przetwarzania, okres przechowywania i udostępnianie" : "4. Processing, retention and sharing"}</h2>
      <p>{ru ? "Обработка осуществляется автоматизированным и неавтоматизированным способом. Данные хранятся не дольше, чем этого требуют цели обработки или применимое законодательство. Доступ получают только уполномоченные лица и подрядчики, которым данные необходимы для работы сайта и коммуникации. Оператор не продаёт персональные данные." : pl ? "Dane mogą być przetwarzane elektronicznie lub ręcznie i są przechowywane tylko tak długo, jak wymaga tego cel przetwarzania lub obowiązujące prawo. Dostęp mają wyłącznie upoważnione osoby i dostawcy niezbędni do działania serwisu i komunikacji. Nie sprzedajemy danych osobowych." : "Data may be processed electronically or manually and is retained only as long as necessary. Access is limited to authorized staff and service providers supporting the website and communications. Personal data is never sold."}</p>
      <h2>{ru ? "5. Защита данных" : pl ? "5. Bezpieczeństwo danych" : "5. Data security"}</h2>
      <p>{ru ? "Оператор применяет организационные и технические меры защиты от неправомерного доступа, изменения, блокирования, копирования и распространения данных, включая ограничение доступа, защищённую передачу и контроль инфраструктуры." : pl ? "Stosujemy środki organizacyjne i techniczne chroniące przed nieuprawnionym dostępem, zmianą, utratą lub ujawnieniem danych, w tym kontrolę dostępu, szyfrowaną transmisję i monitoring infrastruktury." : "The Controller uses organizational and technical safeguards against unauthorized access, alteration, loss or disclosure, including access controls, secure transmission and infrastructure monitoring."}</p>
      <h2>{ru ? "6. Права пользователя" : pl ? "6. Twoje prawa" : "6. Your rights"}</h2>
      <p>{ru ? <>Пользователь вправе запросить сведения об обработке, уточнение, блокирование или удаление данных, а также отозвать согласие. Для этого необходимо направить обращение на <RegionalEmail />. Оператор ответит в срок, установленный применимым законодательством.</> : pl ? <>Masz prawo żądać dostępu do danych, ich sprostowania, ograniczenia przetwarzania lub usunięcia, a także wycofać zgodę. W tym celu napisz na <RegionalEmail />.</> : <>You may request access, correction, restriction or deletion of your data and may withdraw consent by emailing <RegionalEmail />.</>}</p>
      <h2>{ru ? "7. Cookie и аналитика" : pl ? "7. Pliki cookie i analityka" : "7. Cookies and analytics"}</h2>
      <p>{ru ? "Сайт может использовать необходимые cookie для корректной работы и аналитические cookie после получения соответствующего согласия. Пользователь может ограничить cookie в настройках браузера." : pl ? "Serwis może wykorzystywać niezbędne pliki cookie, a po uzyskaniu odpowiedniej zgody także pliki analityczne. Ustawienia cookie można ograniczyć w przeglądarce." : "The website may use essential cookies and, with appropriate consent, analytics cookies. Cookies can be restricted in browser settings."}</p>
      <h2>{ru ? "8. Контакты Оператора" : pl ? "8. Kontakt z Administratorem" : "8. Controller contacts"}</h2>
      <p>Agile Business<br /><RegionalContactDetails /></p>
      <p className="legal-note">{ru ? "При изменении юридических реквизитов Оператора актуальная информация публикуется в этой Политике до начала соответствующей обработки." : pl ? "Aktualne dane Administratora zostaną opublikowane w niniejszej Polityce przed rozpoczęciem odpowiedniego przetwarzania." : "Updated controller details will be published in this Policy before the relevant processing begins."}</p>
    </article>
  );
}
