import type { Locale } from "@/lib/i18n";

const en = {
  title: "Client account", clientSpace: "Your project workspace", login: "Sign in", register: "Register", name: "Name", email: "Email", phone: "Phone", password: "Password", newPassword: "New password", error: "Check your details and try again.", cart: "Service cart", logout: "Sign out", forgot: "Forgot password?", backToLogin: "Back to sign in", recovery: "Restore access", recoveryText: "Enter your account email. We will send a secure link valid for 30 minutes.", sendLink: "Send reset link", resetSent: "If the account exists, a reset link has been sent.", reset: "Set a new password", resetText: "Create a new password with at least 8 characters.", resetSuccess: "Password updated. You can now sign in.", overview: "Overview", active: "Active", approval: "Awaiting approval", completed: "Completed", savedCount: "Saved", activeProjects: "Projects in progress", completedProjects: "Completed projects", emptyTitle: "No active projects yet", emptyText: "Save services from the catalogue and submit the project when you are ready.", choose: "Choose services", scope: "Project scope", paymentPending: "The project timeline will open after payment is confirmed.", paymentRefunded: "Payment refunded", teamConfirmed: "Confirmed by Agile Business", clientConfirmed: "Accepted by you", waitingTeam: "Waiting for the team to submit this stage", approveStage: "Accept stage", approvedStage: "Stage accepted", approvalError: "Could not accept the stage. Please try again.", profile: "Personal details", profileText: "These details are used for project documents and notifications.", changePhoto: "Upload photo", photoHint: "JPG, PNG or WebP. The image is compressed before saving.", saveProfile: "Save details", profileSaved: "Details saved", profileError: "Could not save the profile.", drafts: "Saved services", draftsText: "Services in the cart remain a draft until you submit the project.", noDrafts: "Nothing saved yet", openCart: "Open draft", remove: "Remove", promos: "Promocodes", promosEmpty: "No active promocodes", promosText: "Personal offers will appear here and will be linked to your next order.", security: "Account access", securityText: "A password reset link will be sent to your email and expires after 30 minutes.", sendRecovery: "Email reset link", recoveryQueued: "Reset email requested", reviewTitle: "Your project review", reviewText: "A review becomes available only after all stages are complete.", reviewPlaceholder: "Tell us about the result and your experience with the team", sendReview: "Submit review", reviewSaved: "Thank you — your review has been saved.", reviewError: "Could not save the review.", orderNumber: "Order", noCompleted: "Completed projects will appear here.",
  stages: { NEW: "Request", DISCOVERY: "Discovery", PLANNING: "Planning", DESIGN: "Design", DEVELOPMENT: "Development", QA: "QA", LAUNCH: "Launch", SUPPORT: "Support", COMPLETED: "Complete", CANCELLED: "Cancelled" },
};

type Widen<T> = T extends string ? string : T extends Record<string, unknown> ? { [K in keyof T]: Widen<T[K]> } : T;
export type AccountCopy = Widen<typeof en>;

const ru: AccountCopy = {
  title: "Личный кабинет", clientSpace: "Рабочее пространство клиента", login: "Войти", register: "Регистрация", name: "Имя", email: "Почта", phone: "Телефон", password: "Пароль", newPassword: "Новый пароль", error: "Проверьте данные и попробуйте снова.", cart: "Корзина услуг", logout: "Выйти", forgot: "Забыли пароль?", backToLogin: "Вернуться ко входу", recovery: "Восстановить доступ", recoveryText: "Укажите почту учётной записи. Мы отправим защищённую ссылку, которая действует 30 минут.", sendLink: "Отправить ссылку", resetSent: "Если учётная запись существует, письмо со ссылкой уже отправлено.", reset: "Задать новый пароль", resetText: "Придумайте новый пароль длиной не менее 8 символов.", resetSuccess: "Пароль обновлён. Теперь можно войти.", overview: "Сводка", active: "В работе", approval: "Ждут приёмки", completed: "Завершено", savedCount: "Отложено", activeProjects: "Проекты в работе", completedProjects: "Завершённые проекты", emptyTitle: "Активных проектов пока нет", emptyText: "Сохраните услуги из каталога и отправьте состав проекта, когда будете готовы.", choose: "Выбрать услуги", scope: "Состав проекта", paymentPending: "Этапы проекта откроются после подтверждения оплаты.", paymentRefunded: "Оплата возвращена", teamConfirmed: "Подтверждено Agile Business", clientConfirmed: "Принято вами", waitingTeam: "Ждём, когда команда передаст этап на приёмку", approveStage: "Принять этап", approvedStage: "Этап принят", approvalError: "Не удалось принять этап. Попробуйте ещё раз.", profile: "Личные данные", profileText: "Эти данные используются в документах по проекту и уведомлениях.", changePhoto: "Загрузить фото", photoHint: "JPG, PNG или WebP. Фото сжимается перед сохранением.", saveProfile: "Сохранить данные", profileSaved: "Данные сохранены", profileError: "Не удалось сохранить профиль.", drafts: "Отложенные услуги", draftsText: "Услуги в корзине остаются черновиком, пока вы не отправите проект.", noDrafts: "Пока ничего не отложено", openCart: "Открыть черновик", remove: "Убрать", promos: "Промокоды", promosEmpty: "Активных промокодов пока нет", promosText: "Персональные предложения появятся здесь и привяжутся к следующему заказу.", security: "Доступ к кабинету", securityText: "Ссылка для смены пароля придёт на почту и будет действовать 30 минут.", sendRecovery: "Отправить ссылку на почту", recoveryQueued: "Письмо на восстановление запрошено", reviewTitle: "Отзыв о проекте", reviewText: "Отзыв можно оставить только после завершения всех этапов.", reviewPlaceholder: "Расскажите о результате и работе с командой", sendReview: "Отправить отзыв", reviewSaved: "Спасибо — отзыв сохранён.", reviewError: "Не удалось сохранить отзыв.", orderNumber: "Заказ", noCompleted: "Завершённые проекты появятся здесь.",
  stages: { NEW: "Заявка", DISCOVERY: "Погружение", PLANNING: "Планирование", DESIGN: "Дизайн", DEVELOPMENT: "Разработка", QA: "Проверка", LAUNCH: "Запуск", SUPPORT: "Поддержка", COMPLETED: "Готово", CANCELLED: "Отменён" },
};

const pl: AccountCopy = {
  title: "Panel klienta", clientSpace: "Przestrzeń Twojego projektu", login: "Zaloguj się", register: "Załóż konto", name: "Imię i nazwisko", email: "E-mail", phone: "Telefon", password: "Hasło", newPassword: "Nowe hasło", error: "Sprawdź dane i spróbuj ponownie.", cart: "Koszyk usług", logout: "Wyloguj się", forgot: "Nie pamiętasz hasła?", backToLogin: "Wróć do logowania", recovery: "Odzyskaj dostęp", recoveryText: "Wpisz adres e-mail konta. Wyślemy bezpieczny link ważny przez 30 minut.", sendLink: "Wyślij link", resetSent: "Jeśli konto istnieje, wysłaliśmy wiadomość z linkiem do zmiany hasła.", reset: "Ustaw nowe hasło", resetText: "Utwórz nowe hasło składające się z co najmniej 8 znaków.", resetSuccess: "Hasło zostało zmienione. Możesz się teraz zalogować.", overview: "Podsumowanie", active: "W realizacji", approval: "Do akceptacji", completed: "Zakończone", savedCount: "Zapisane", activeProjects: "Aktywne projekty", completedProjects: "Zakończone projekty", emptyTitle: "Nie masz jeszcze aktywnych projektów", emptyText: "Zapisz usługi z katalogu i wyślij projekt, gdy zakres będzie gotowy.", choose: "Wybierz usługi", scope: "Zakres projektu", paymentPending: "Harmonogram projektu pojawi się po potwierdzeniu płatności.", paymentRefunded: "Płatność zwrócona", teamConfirmed: "Potwierdzone przez Agile Business", clientConfirmed: "Zaakceptowane przez Ciebie", waitingTeam: "Czekamy, aż zespół przekaże etap do odbioru", approveStage: "Zaakceptuj etap", approvedStage: "Etap zaakceptowany", approvalError: "Nie udało się zaakceptować etapu. Spróbuj ponownie.", profile: "Dane osobowe", profileText: "Te dane wykorzystujemy w dokumentacji projektu i powiadomieniach.", changePhoto: "Prześlij zdjęcie", photoHint: "JPG, PNG lub WebP. Obraz zostanie skompresowany przed zapisem.", saveProfile: "Zapisz dane", profileSaved: "Dane zostały zapisane", profileError: "Nie udało się zapisać profilu.", drafts: "Zapisane usługi", draftsText: "Usługi w koszyku pozostają wersją roboczą do chwili wysłania projektu.", noDrafts: "Nie masz jeszcze zapisanych usług", openCart: "Otwórz wersję roboczą", remove: "Usuń", promos: "Kody promocyjne", promosEmpty: "Brak aktywnych kodów promocyjnych", promosText: "Spersonalizowane oferty pojawią się tutaj i zostaną przypisane do kolejnego zamówienia.", security: "Dostęp do konta", securityText: "Link do zmiany hasła zostanie wysłany na Twój e-mail i wygaśnie po 30 minutach.", sendRecovery: "Wyślij link do zmiany hasła", recoveryQueued: "Poproszono o wiadomość do zmiany hasła", reviewTitle: "Opinia o projekcie", reviewText: "Opinię możesz dodać dopiero po zakończeniu wszystkich etapów.", reviewPlaceholder: "Opowiedz o rezultacie i współpracy z zespołem", sendReview: "Wyślij opinię", reviewSaved: "Dziękujemy — opinia została zapisana.", reviewError: "Nie udało się zapisać opinii.", orderNumber: "Zamówienie", noCompleted: "Zakończone projekty pojawią się tutaj.",
  stages: { NEW: "Zgłoszenie", DISCOVERY: "Diagnoza", PLANNING: "Planowanie", DESIGN: "Projektowanie", DEVELOPMENT: "Realizacja", QA: "Weryfikacja", LAUNCH: "Uruchomienie", SUPPORT: "Wsparcie", COMPLETED: "Zakończony", CANCELLED: "Anulowany" },
};

const bg: AccountCopy = {
  ...en,
  title: "Клиентски профил", clientSpace: "Работно пространство на клиента", login: "Вход", register: "Регистрация", name: "Име", phone: "Телефон", password: "Парола", newPassword: "Нова парола", cart: "Количка с услуги", logout: "Изход", forgot: "Забравена парола?", backToLogin: "Назад към вход", recovery: "Възстановяване на достъпа", recoveryText: "Въведете имейла на профила. Ще изпратим защитена връзка, валидна 30 минути.", sendLink: "Изпрати връзка", reset: "Задаване на нова парола", overview: "Обобщение", active: "В работа", approval: "За одобрение", completed: "Завършени", savedCount: "Запазени", activeProjects: "Активни проекти", completedProjects: "Завършени проекти", choose: "Избери услуги", scope: "Обхват на проекта", teamConfirmed: "Потвърдено от Agile Business", clientConfirmed: "Прието от вас", approveStage: "Приеми етапа", approvedStage: "Етапът е приет", profile: "Лични данни", saveProfile: "Запази данните", drafts: "Запазени услуги", openCart: "Отвори черновата", promos: "Промокодове", security: "Достъп до профила", sendRecovery: "Изпрати връзка по имейл", reviewTitle: "Отзив за проекта", sendReview: "Изпрати отзив",
  stages: { NEW: "Заявка", DISCOVERY: "Проучване", PLANNING: "Планиране", DESIGN: "Дизайн", DEVELOPMENT: "Разработка", QA: "Проверка", LAUNCH: "Стартиране", SUPPORT: "Поддръжка", COMPLETED: "Завършен", CANCELLED: "Отменен" },
};

const ka: AccountCopy = {
  ...en,
  title: "პირადი კაბინეტი", clientSpace: "კლიენტის სამუშაო სივრცე", login: "შესვლა", register: "რეგისტრაცია", name: "სახელი", phone: "ტელეფონი", password: "პაროლი", newPassword: "ახალი პაროლი", cart: "სერვისების კალათა", logout: "გასვლა", forgot: "დაგავიწყდათ პაროლი?", backToLogin: "შესვლაზე დაბრუნება", recovery: "წვდომის აღდგენა", sendLink: "ბმულის გაგზავნა", overview: "მიმოხილვა", active: "მიმდინარე", approval: "დასადასტურებელი", completed: "დასრულებული", savedCount: "შენახული", activeProjects: "მიმდინარე პროექტები", completedProjects: "დასრულებული პროექტები", choose: "სერვისების არჩევა", scope: "პროექტის შემადგენლობა", teamConfirmed: "დადასტურებულია Agile Business-ის მიერ", clientConfirmed: "თქვენ მიერ მიღებულია", approveStage: "ეტაპის მიღება", approvedStage: "ეტაპი მიღებულია", profile: "პირადი მონაცემები", saveProfile: "მონაცემების შენახვა", drafts: "შენახული სერვისები", openCart: "შავი ვერსიის გახსნა", promos: "პრომოკოდები", security: "კაბინეტზე წვდომა", sendRecovery: "აღდგენის ბმულის გაგზავნა", reviewTitle: "პროექტის შეფასება", sendReview: "შეფასების გაგზავნა",
  stages: { NEW: "მოთხოვნა", DISCOVERY: "კვლევა", PLANNING: "დაგეგმვა", DESIGN: "დიზაინი", DEVELOPMENT: "დეველოპმენტი", QA: "შემოწმება", LAUNCH: "გაშვება", SUPPORT: "მხარდაჭერა", COMPLETED: "დასრულებული", CANCELLED: "გაუქმებული" },
};

const hy: AccountCopy = {
  ...en,
  title: "Անձնական հաշիվ", clientSpace: "Հաճախորդի աշխատանքային տարածք", login: "Մուտք", register: "Գրանցում", name: "Անուն", phone: "Հեռախոս", password: "Գաղտնաբառ", newPassword: "Նոր գաղտնաբառ", cart: "Ծառայությունների զամբյուղ", logout: "Դուրս գալ", forgot: "Մոռացե՞լ եք գաղտնաբառը", backToLogin: "Վերադառնալ մուտքին", recovery: "Վերականգնել մուտքը", sendLink: "Ուղարկել հղումը", overview: "Ամփոփում", active: "Ընթացիկ", approval: "Ընդունման", completed: "Ավարտված", savedCount: "Պահված", activeProjects: "Ընթացիկ նախագծեր", completedProjects: "Ավարտված նախագծեր", choose: "Ընտրել ծառայություններ", scope: "Նախագծի կազմ", teamConfirmed: "Հաստատված է Agile Business-ի կողմից", clientConfirmed: "Ընդունված է ձեր կողմից", approveStage: "Ընդունել փուլը", approvedStage: "Փուլն ընդունված է", profile: "Անձնական տվյալներ", saveProfile: "Պահպանել տվյալները", drafts: "Պահված ծառայություններ", openCart: "Բացել սևագիրը", promos: "Պրոմոկոդեր", security: "Հաշվի հասանելիություն", sendRecovery: "Ուղարկել վերականգնման հղումը", reviewTitle: "Նախագծի կարծիք", sendReview: "Ուղարկել կարծիքը",
  stages: { NEW: "Հայտ", DISCOVERY: "Ուսումնասիրություն", PLANNING: "Պլանավորում", DESIGN: "Դիզայն", DEVELOPMENT: "Մշակում", QA: "Ստուգում", LAUNCH: "Մեկնարկ", SUPPORT: "Աջակցություն", COMPLETED: "Ավարտված", CANCELLED: "Չեղարկված" },
};

export function getAccountCopy(locale: Locale): AccountCopy {
  return locale === "ru" ? ru : locale === "pl" ? pl : locale === "bg" ? bg : locale === "ka" ? ka : locale === "hy" ? hy : en;
}
