export const locales = ["ru", "en", "ka", "hy", "bg"] as const;
export type Locale = (typeof locales)[number];
export const defaultLocale: Locale = "ru";

export const localeNames: Record<Locale, string> = {
  ru: "RU",
  en: "EN",
  ka: "KA",
  hy: "HY",
  bg: "BG",
};

export function isLocale(value: string): value is Locale {
  return locales.includes(value as Locale);
}

const dictionaries = {
  ru: {
    nav: { services: "Услуги", about: "О нас", calculator: "Калькулятор", contacts: "Контакты", cta: "Обсудить проект" },
    hero: { eyebrow: "Бизнес-консалтинг нового поколения", title: "Решения под задачи бизнеса.", accent: "От диагностики до результата.", text: "Объединяем аналитику, стратегию и технологии, чтобы компании принимали точные решения и быстрее масштабировались.", primary: "Рассчитать проект", secondary: "Смотреть услуги" },
    stats: [["3", "направления экспертизы"], ["20+", "реализованных проектов"], ["98%", "клиентов рекомендуют"]],
    services: { eyebrow: "Экспертиза", title: "Работаем с бизнесом системно", text: "Не продаём отдельные отчёты и инструменты. Разбираемся в задаче, проектируем решение и сопровождаем внедрение.", items: [["01", "Бизнес-аналитика", "Диагностика процессов, управленческие метрики, BI и решения на основе данных."], ["02", "ИТ и разработка", "Цифровые продукты, корпоративные системы, интеграции и автоматизация."], ["03", "Стратегия и рост", "Позиционирование, go-to-market, маркетинг и управляемое масштабирование."]] },
    method: { eyebrow: "Подход", title: "Ясный процесс без лишней бюрократии", steps: [["Диагностика", "Фиксируем исходную точку, ограничения и измеримые цели."], ["Стратегия", "Собираем решение, приоритеты, сроки и экономику проекта."], ["Внедрение", "Работаем короткими итерациями и показываем промежуточный результат."], ["Масштабирование", "Измеряем эффект, улучшаем систему и передаём её команде."]] },
    cta: { title: "Есть задача, которую пора решить?", text: "Опишите контекст. Вернёмся с уточняющими вопросами и предложим решение.", button: "Начать обсуждение" },
    footer: { line: "Комплексный консалтинг с измеримым результатом", privacy: "Политика конфиденциальности" },
    page: { servicesTitle: "Услуги для трансформации и роста", servicesText: "Собираем проект под конкретную бизнес-задачу: от исследования до внедрения и измерения эффекта.", aboutTitle: "Agile Business. Команда на стороне результата", aboutText: "Объединяем бизнес-анализ, стратегию и разработку. Работаем напрямую с собственниками и командами, сохраняя прозрачность решений, сроков и бюджета.", aboutPrinciples: ["Сначала бизнес-задача, затем инструмент", "Измеримый результат вместо формального отчёта", "Прямой контакт с экспертами", "Решение остаётся работоспособным после проекта"], contactsTitle: "Давайте обсудим задачу", contactsText: "Расскажите, что хотите изменить в бизнесе. Ответим в течение рабочего дня.", calculatorTitle: "Предварительный расчёт проекта", calculatorText: "Оценка помогает определить диапазон бюджета. Финальная стоимость формируется после короткой диагностики." },
    form: { name: "Ваше имя", email: "Рабочая почта", phone: "Телефон", company: "Компания", message: "Кратко опишите задачу", consent: "Отправляя форму, вы соглашаетесь с политикой обработки персональных данных.", submit: "Отправить", sending: "Отправляем…", success: "Спасибо. Заявка принята — скоро свяжемся.", error: "Не удалось отправить. Напишите нам на info@agile-business-pro.com" },
    calc: { service: "Направление", size: "Размер компании", complexity: "Формат работы", duration: "Срок", task: "Описание задачи", next: "Далее", back: "Назад", calculate: "Получить оценку", result: "Предварительная стоимость", disclaimer: "Диапазон не является публичной офертой и уточняется после диагностики.", leave: "Получить точное предложение", options: { analytics: "Бизнес-аналитика", it: "ИТ и разработка", strategy: "Стратегия и рост", small: "Малый бизнес", medium: "Средний бизнес", large: "Крупный бизнес", basic: "Диагностика", standard: "Разработка и внедрение", premium: "Полное сопровождение", short: "1–3 месяца", mid: "3–6 месяцев", long: "6–12 месяцев" } },
  },
  en: {
    nav: { services: "Services", about: "About", calculator: "Estimator", contacts: "Contact", cta: "Discuss a project" },
    hero: { eyebrow: "Next-generation business consulting", title: "Solutions built around business goals.", accent: "From diagnosis to measurable impact.", text: "We combine analytics, strategy and technology to help companies make better decisions and scale faster.", primary: "Estimate a project", secondary: "Explore services" },
    stats: [["3", "areas of expertise"], ["20+", "delivered projects"], ["98%", "client recommendation rate"]],
    services: { eyebrow: "Expertise", title: "A systematic approach to business", text: "We do not sell isolated reports or tools. We diagnose the problem, design the solution and support implementation.", items: [["01", "Business analytics", "Process diagnostics, management metrics, BI and data-driven decisions."], ["02", "IT & development", "Digital products, enterprise systems, integrations and automation."], ["03", "Strategy & growth", "Positioning, go-to-market, marketing and controlled scaling."]] },
    method: { eyebrow: "Approach", title: "A clear process without unnecessary bureaucracy", steps: [["Diagnosis", "Define the starting point, constraints and measurable goals."], ["Strategy", "Design the solution, priorities, timeline and project economics."], ["Implementation", "Work in short iterations and demonstrate progress early."], ["Scaling", "Measure impact, improve the system and transfer it to your team."]] },
    cta: { title: "Have a challenge worth solving?", text: "Share the context and we will come back with focused questions and a practical next step.", button: "Start a conversation" },
    footer: { line: "Business consulting with measurable impact", privacy: "Privacy policy" },
    page: { servicesTitle: "Services for transformation and growth", servicesText: "Every engagement is built around a specific business objective — from research to implementation and impact measurement.", aboutTitle: "Agile Business is a team focused on outcomes", aboutText: "We bring together business analysis, strategy and development. We work directly with owners and teams, keeping decisions, timing and budgets transparent.", aboutPrinciples: ["Business objective first, tool second", "Measurable impact over formal reports", "Direct access to experts", "Solutions that keep working after the engagement"], contactsTitle: "Let’s discuss your challenge", contactsText: "Tell us what you want to change in your business. We reply within one business day.", calculatorTitle: "Preliminary project estimate", calculatorText: "The estimate helps define a budget range. Final pricing follows a short discovery session." },
    form: { name: "Your name", email: "Work email", phone: "Phone", company: "Company", message: "Briefly describe the challenge", consent: "By submitting, you agree to our personal data policy.", submit: "Send request", sending: "Sending…", success: "Thank you. We received your request and will be in touch.", error: "Could not send the form. Email us at info@agile-business-pro.com" },
    calc: { service: "Service", size: "Company size", complexity: "Engagement format", duration: "Timeline", task: "Challenge", next: "Next", back: "Back", calculate: "Get estimate", result: "Preliminary estimate", disclaimer: "This range is not a public offer and is refined after discovery.", leave: "Request a detailed proposal", options: { analytics: "Business analytics", it: "IT & development", strategy: "Strategy & growth", small: "Small business", medium: "Mid-market", large: "Enterprise", basic: "Diagnosis", standard: "Design & implementation", premium: "Full support", short: "1–3 months", mid: "3–6 months", long: "6–12 months" } },
  },
} as const;

type Dictionary = (typeof dictionaries)[keyof typeof dictionaries];

const regional = {
  ka: {
    nav: { services: "სერვისები", about: "ჩვენ შესახებ", calculator: "კალკულატორი", contacts: "კონტაქტი", cta: "პროექტის განხილვა" },
    hero: { eyebrow: "ახალი თაობის ბიზნეს კონსალტინგი", title: "გადაწყვეტილებები ბიზნესის ამოცანებისთვის.", accent: "დიაგნოსტიკიდან შედეგამდე.", text: "ვაერთიანებთ ანალიტიკას, სტრატეგიასა და ტექნოლოგიებს უკეთესი გადაწყვეტილებებისა და სწრაფი ზრდისთვის.", primary: "პროექტის შეფასება", secondary: "სერვისები" },
    stats: [["3", "ექსპერტიზის მიმართულება"], ["20+", "განხორციელებული პროექტი"], ["98%", "კლიენტების რეკომენდაცია"]],
    services: { eyebrow: "ექსპერტიზა", title: "ბიზნესთან სისტემურად ვმუშაობთ", text: "არ ვყიდით ცალკეულ ანგარიშებს ან ინსტრუმენტებს. ვიკვლევთ ამოცანას, ვქმნით გადაწყვეტას და მხარს ვუჭერთ დანერგვას.", items: [["01", "ბიზნეს ანალიტიკა", "პროცესების დიაგნოსტიკა, მენეჯმენტის მეტრიკები, BI და მონაცემებზე დაფუძნებული გადაწყვეტილებები."], ["02", "IT და დეველოპმენტი", "ციფრული პროდუქტები, კორპორაციული სისტემები, ინტეგრაციები და ავტომატიზაცია."], ["03", "სტრატეგია და ზრდა", "პოზიციონირება, ბაზარზე გასვლა, მარკეტინგი და მართვადი მასშტაბირება."]] },
    method: { eyebrow: "მიდგომა", title: "გასაგები პროცესი ზედმეტი ბიუროკრატიის გარეშე", steps: [["დიაგნოსტიკა", "ვადგენთ საწყის მდგომარეობას, შეზღუდვებსა და გაზომვად მიზნებს."], ["სტრატეგია", "ვქმნით გადაწყვეტას, პრიორიტეტებს, ვადებსა და პროექტის ეკონომიკას."], ["დანერგვა", "ვმუშაობთ მოკლე იტერაციებით და შედეგს ადრევე ვაჩვენებთ."], ["მასშტაბირება", "ვზომავთ ეფექტს, ვაუმჯობესებთ სისტემას და გადავცემთ გუნდს."]] },
    cta: { title: "გაქვთ ამოცანა, რომლის გადაწყვეტაც დროა?", text: "გაგვიზიარეთ კონტექსტი — დაგიბრუნდებით ზუსტი კითხვებით და პრაქტიკული შემდეგი ნაბიჯით.", button: "საუბრის დაწყება" },
    footer: { line: "ბიზნეს კონსალტინგი გაზომვადი შედეგით", privacy: "კონფიდენციალურობის პოლიტიკა" },
    page: { servicesTitle: "სერვისები ტრანსფორმაციისა და ზრდისთვის", servicesText: "ყველა პროექტს ვაწყობთ კონკრეტული ბიზნეს მიზნის გარშემო — კვლევიდან დანერგვამდე და ეფექტის გაზომვამდე.", aboutTitle: "Agile Business — შედეგზე ორიენტირებული გუნდი", aboutText: "ვაერთიანებთ ბიზნეს ანალიზს, სტრატეგიასა და დეველოპმენტს. უშუალოდ ვმუშაობთ მფლობელებსა და გუნდებთან, გამჭვირვალედ ვმართავთ გადაწყვეტილებებს, ვადებსა და ბიუჯეტს.", aboutPrinciples: ["ჯერ ბიზნეს მიზანი, შემდეგ ინსტრუმენტი", "გაზომვადი ეფექტი ფორმალური ანგარიშის ნაცვლად", "პირდაპირი კავშირი ექსპერტებთან", "გადაწყვეტილება მუშაობას პროექტის შემდეგაც აგრძელებს"], contactsTitle: "განვიხილოთ თქვენი ამოცანა", contactsText: "გვიამბეთ, რისი შეცვლა გსურთ ბიზნესში. ერთ სამუშაო დღეში გიპასუხებთ.", calculatorTitle: "პროექტის წინასწარი შეფასება", calculatorText: "შეფასება განსაზღვრავს ბიუჯეტის დიაპაზონს. საბოლოო ღირებულება მოკლე დიაგნოსტიკის შემდეგ დგინდება." },
    form: { name: "თქვენი სახელი", email: "სამუშაო ელფოსტა", phone: "ტელეფონი", company: "კომპანია", message: "მოკლედ აღწერეთ ამოცანა", consent: "ფორმის გაგზავნით ეთანხმებით პერსონალური მონაცემების პოლიტიკას.", submit: "გაგზავნა", sending: "იგზავნება…", success: "გმადლობთ. მოთხოვნა მიღებულია — მალე დაგიკავშირდებით.", error: "ფორმა ვერ გაიგზავნა. მოგვწერეთ info@agile-business-pro.com-ზე" },
    calc: { service: "მიმართულება", size: "კომპანიის ზომა", complexity: "თანამშრომლობის ფორმატი", duration: "ვადა", task: "ამოცანის აღწერა", next: "შემდეგი", back: "უკან", calculate: "შეფასების მიღება", result: "წინასწარი ღირებულება", disclaimer: "დიაპაზონი არ არის საჯარო შეთავაზება და ზუსტდება დიაგნოსტიკის შემდეგ.", leave: "დეტალური შეთავაზების მიღება", options: { analytics: "ბიზნეს ანალიტიკა", it: "IT და დეველოპმენტი", strategy: "სტრატეგია და ზრდა", small: "მცირე ბიზნესი", medium: "საშუალო ბიზნესი", large: "მსხვილი ბიზნესი", basic: "დიაგნოსტიკა", standard: "შექმნა და დანერგვა", premium: "სრული მხარდაჭერა", short: "1–3 თვე", mid: "3–6 თვე", long: "6–12 თვე" } },
  },
  hy: {
    nav: { services: "Ծառայություններ", about: "Մեր մասին", calculator: "Հաշվիչ", contacts: "Կապ", cta: "Քննարկել նախագիծը" },
    hero: { eyebrow: "Նոր սերնդի բիզնես խորհրդատվություն", title: "Լուծումներ բիզնեսի խնդիրների համար։", accent: "Ախտորոշումից մինչև արդյունք։", text: "Միավորում ենք վերլուծությունը, ռազմավարությունն ու տեխնոլոգիաները՝ ճշգրիտ որոշումների և արագ աճի համար։", primary: "Գնահատել նախագիծը", secondary: "Ծառայություններ" },
    stats: [["3", "փորձագիտական ուղղություն"], ["20+", "իրականացված նախագիծ"], ["98%", "հաճախորդների խորհուրդ"]],
    services: { eyebrow: "Փորձագիտություն", title: "Բիզնեսի հետ աշխատում ենք համակարգված", text: "Մենք չենք վաճառում առանձին հաշվետվություններ կամ գործիքներ։ Ուսումնասիրում ենք խնդիրը, նախագծում լուծումը և աջակցում ներդրմանը։", items: [["01", "Բիզնես վերլուծություն", "Գործընթացների ախտորոշում, կառավարման չափանիշներ, BI և տվյալահեն որոշումներ։"], ["02", "ՏՏ և մշակում", "Թվային արտադրանք, կորպորատիվ համակարգեր, ինտեգրումներ և ավտոմատացում։"], ["03", "Ռազմավարություն և աճ", "Դիրքավորում, շուկա մուտք, մարքեթինգ և կառավարվող մասշտաբավորում։"]] },
    method: { eyebrow: "Մոտեցում", title: "Հստակ գործընթաց՝ առանց ավելորդ բյուրոկրատիայի", steps: [["Ախտորոշում", "Սահմանում ենք մեկնարկային կետը, սահմանափակումներն ու չափելի նպատակները։"], ["Ռազմավարություն", "Կառուցում ենք լուծումը, առաջնահերթությունները, ժամկետներն ու տնտեսագիտությունը։"], ["Ներդրում", "Աշխատում ենք կարճ փուլերով և շուտ ցույց տալիս արդյունքը։"], ["Մասշտաբավորում", "Չափում ենք ազդեցությունը, բարելավում համակարգը և փոխանցում թիմին։"]] },
    cta: { title: "Ունե՞ք խնդիր, որը ժամանակն է լուծել։", text: "Նկարագրեք համատեքստը․ մենք կվերադառնանք հստակ հարցերով և գործնական հաջորդ քայլով։", button: "Սկսել քննարկումը" },
    footer: { line: "Բիզնես խորհրդատվություն՝ չափելի արդյունքով", privacy: "Գաղտնիության քաղաքականություն" },
    page: { servicesTitle: "Ծառայություններ վերափոխման և աճի համար", servicesText: "Յուրաքանչյուր նախագիծ կառուցում ենք կոնկրետ բիզնես նպատակի շուրջ՝ հետազոտությունից մինչև ներդրում և ազդեցության չափում։", aboutTitle: "Agile Business՝ արդյունքի վրա կենտրոնացած թիմ", aboutText: "Միավորում ենք բիզնես վերլուծությունը, ռազմավարությունն ու մշակումը։ Անմիջական աշխատում ենք սեփականատերերի և թիմերի հետ՝ թափանցիկ պահելով որոշումները, ժամկետներն ու բյուջեն։", aboutPrinciples: ["Նախ բիզնես նպատակը, հետո գործիքը", "Չափելի ազդեցություն՝ ձևական հաշվետվության փոխարեն", "Ուղիղ կապ փորձագետների հետ", "Լուծումը շարունակում է աշխատել նախագծից հետո"], contactsTitle: "Քննարկենք ձեր խնդիրը", contactsText: "Պատմեք, թե ինչ եք ցանկանում փոխել բիզնեսում։ Կպատասխանենք մեկ աշխատանքային օրվա ընթացքում։", calculatorTitle: "Նախագծի նախնական գնահատում", calculatorText: "Գնահատումը սահմանում է բյուջեի միջակայքը։ Վերջնական գինը ձևավորվում է կարճ ախտորոշումից հետո։" },
    form: { name: "Ձեր անունը", email: "Աշխատանքային էլ․ հասցե", phone: "Հեռախոս", company: "Ընկերություն", message: "Համառոտ նկարագրեք խնդիրը", consent: "Ուղարկելով ձևը՝ համաձայնում եք անձնական տվյալների քաղաքականությանը։", submit: "Ուղարկել", sending: "Ուղարկվում է…", success: "Շնորհակալություն։ Հայտը ստացվել է, շուտով կապ կհաստատենք։", error: "Չհաջողվեց ուղարկել։ Գրեք info@agile-business-pro.com հասցեին" },
    calc: { service: "Ուղղություն", size: "Ընկերության չափ", complexity: "Աշխատանքի ձևաչափ", duration: "Ժամկետ", task: "Խնդրի նկարագրություն", next: "Հաջորդը", back: "Հետ", calculate: "Ստանալ գնահատում", result: "Նախնական արժեք", disclaimer: "Միջակայքը հրապարակային առաջարկ չէ և ճշտվում է ախտորոշումից հետո։", leave: "Ստանալ մանրամասն առաջարկ", options: { analytics: "Բիզնես վերլուծություն", it: "ՏՏ և մշակում", strategy: "Ռազմավարություն և աճ", small: "Փոքր բիզնես", medium: "Միջին բիզնես", large: "Խոշոր բիզնես", basic: "Ախտորոշում", standard: "Նախագծում և ներդրում", premium: "Ամբողջական աջակցություն", short: "1–3 ամիս", mid: "3–6 ամիս", long: "6–12 ամիս" } },
  },
  bg: {
    nav: { services: "Услуги", about: "За нас", calculator: "Калкулатор", contacts: "Контакти", cta: "Обсъждане на проект" },
    hero: { eyebrow: "Бизнес консултиране от ново поколение", title: "Решения за бизнес задачи.", accent: "От диагностиката до резултата.", text: "Обединяваме анализи, стратегия и технологии за по-точни решения и по-бърз растеж.", primary: "Оценка на проект", secondary: "Вижте услугите" },
    stats: [["3", "области на експертиза"], ["20+", "реализирани проекта"], ["98%", "клиенти ни препоръчват"]],
    services: { eyebrow: "Експертиза", title: "Работим с бизнеса системно", text: "Не продаваме отделни доклади или инструменти. Анализираме задачата, проектираме решението и подпомагаме внедряването.", items: [["01", "Бизнес анализи", "Диагностика на процеси, управленски показатели, BI и решения, базирани на данни."], ["02", "ИТ и разработка", "Дигитални продукти, корпоративни системи, интеграции и автоматизация."], ["03", "Стратегия и растеж", "Позициониране, излизане на пазара, маркетинг и контролирано мащабиране."]] },
    method: { eyebrow: "Подход", title: "Ясен процес без излишна бюрокрация", steps: [["Диагностика", "Определяме началната точка, ограниченията и измеримите цели."], ["Стратегия", "Изграждаме решението, приоритетите, сроковете и икономиката на проекта."], ["Внедряване", "Работим на кратки итерации и показваме резултат рано."], ["Мащабиране", "Измерваме ефекта, подобряваме системата и я предаваме на екипа."]] },
    cta: { title: "Имате задача, която е време да решите?", text: "Споделете контекста — ще се върнем с точни въпроси и практична следваща стъпка.", button: "Започнете разговор" },
    footer: { line: "Бизнес консултиране с измерим резултат", privacy: "Политика за поверителност" },
    page: { servicesTitle: "Услуги за трансформация и растеж", servicesText: "Изграждаме всеки проект около конкретна бизнес цел — от проучването до внедряването и измерването на ефекта.", aboutTitle: "Agile Business е екип, фокусиран върху резултата", aboutText: "Обединяваме бизнес анализ, стратегия и разработка. Работим директно със собственици и екипи, като поддържаме прозрачност на решенията, сроковете и бюджета.", aboutPrinciples: ["Първо бизнес целта, после инструментът", "Измерим резултат вместо формален доклад", "Директен контакт с експертите", "Решението продължава да работи след проекта"], contactsTitle: "Нека обсъдим вашата задача", contactsText: "Разкажете ни какво искате да промените в бизнеса. Отговаряме в рамките на един работен ден.", calculatorTitle: "Предварителна оценка на проекта", calculatorText: "Оценката помага да се определи бюджетен диапазон. Крайната цена се формира след кратка диагностика." },
    form: { name: "Вашето име", email: "Служебен имейл", phone: "Телефон", company: "Компания", message: "Опишете накратко задачата", consent: "С изпращането се съгласявате с политиката за лични данни.", submit: "Изпрати", sending: "Изпращане…", success: "Благодарим. Заявката е приета — скоро ще се свържем.", error: "Формата не беше изпратена. Пишете на info@agile-business-pro.com" },
    calc: { service: "Направление", size: "Размер на компанията", complexity: "Формат на работа", duration: "Срок", task: "Описание на задачата", next: "Напред", back: "Назад", calculate: "Получаване на оценка", result: "Предварителна стойност", disclaimer: "Диапазонът не е публична оферта и се уточнява след диагностика.", leave: "Получаване на подробна оферта", options: { analytics: "Бизнес анализи", it: "ИТ и разработка", strategy: "Стратегия и растеж", small: "Малък бизнес", medium: "Среден бизнес", large: "Голям бизнес", basic: "Диагностика", standard: "Проектиране и внедряване", premium: "Пълна подкрепа", short: "1–3 месеца", mid: "3–6 месеца", long: "6–12 месеца" } },
  },
} satisfies Record<"ka" | "hy" | "bg", Partial<Record<keyof Dictionary, unknown>>>;

export function getDictionary(locale: Locale): Dictionary {
  if (locale === "ru" || locale === "en") return dictionaries[locale];
  return { ...dictionaries.en, ...regional[locale] } as unknown as Dictionary;
}
